# Generated by Django 3.0.8 on 2020-09-06 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('author', models.CharField(max_length=30, verbose_name='작성자')),
                ('createDate', models.DateField(default=django.utils.timezone.now, verbose_name='작성일')),
            ],
        ),
    ]
